import type { FormSchema } from '@/app/components/form-input/form-generator/form-generator.types';

export function buildUserFormSchema(isEdit: boolean): FormSchema {
  return {
    fields: [
      {
        name: 'username',
        label: 'شناسه فنی',
        type: 'text',
        required: true,
        row: 0,
        lgSpan: 6,
        placeholder: 'شناسه یکتای ورود — مثال: jsmith',
      },
      {
        name: 'email',
        label: 'ایمیل',
        type: 'email',
        required: true,
        row: 0,
        lgSpan: 6,
        placeholder: 'user@example.com',
      },
      {
        name: 'first_name',
        label: 'نام',
        type: 'text',
        required: true,
        row: 1,
        lgSpan: 6,
        placeholder: 'مثال: علی',
      },
      {
        name: 'last_name',
        label: 'نام خانوادگی',
        type: 'text',
        required: true,
        row: 1,
        lgSpan: 6,
        placeholder: 'مثال: اکبری',
      },
      {
        name: 'phone',
        label: 'موبایل',
        type: 'text',
        required: false,
        row: 2,
        lgSpan: 6,
        placeholder: '09123456789',
      },
      {
        name: 'account_number',
        label: 'شماره حساب',
        type: 'text',
        required: false,
        row: 2,
        lgSpan: 6,
        placeholder: 'شماره حساب بانکی (اختیاری)',
      },
      {
        name: 'sheba_number',
        label: 'شماره شبا',
        type: 'text',
        required: false,
        row: 3,
        lgSpan: 6,
        placeholder: 'IR… (اختیاری)',
      },
      {
        name: 'card_number',
        label: 'شماره کارت',
        type: 'text',
        required: false,
        row: 3,
        lgSpan: 6,
        placeholder: '۱۶ رقم (اختیاری)',
      },
      {
        name: 'password',
        label: isEdit ? 'رمز عبور (خالی = بدون تغییر)' : 'رمز عبور',
        type: 'password',
        required: !isEdit,
        row: 4,
        lgSpan: 6,
        placeholder: isEdit ? 'اختیاری — حداقل ۶ کاراکتر' : 'حداقل ۶ کاراکتر',
      },
      {
        name: 'role_id',
        label: 'نقش',
        type: 'custom',
        required: false,
        row: 4,
        lgSpan: 6,
      },
      {
        name: 'department_id',
        label: 'واحد سازمانی',
        type: 'custom',
        required: false,
        row: 5,
        lgSpan: 6,
      },
      {
        name: 'manager_id',
        label: 'مدیر مستقیم',
        type: 'custom',
        required: false,
        row: 5,
        lgSpan: 6,
      },
      {
        name: 'is_active',
        label: 'وضعیت',
        type: 'select',
        required: true,
        row: 6,
        lgSpan: 6,
        options: [
          { label: 'فعال', value: 'true' },
          { label: 'غیرفعال', value: 'false' },
        ],
      },
    ],
  };
}
